### ISSUE TITLE
Tutorial de instalação do PostgreSQL no Ubuntu

### ISSUE THREAD

**Issue by onhernandes** [backend-br/como-instalar-xyz#15]

**Comment by robsonsilv4** [comment]
Vou cobrir todos para o Arch Linux por enquanto, depois adiciono alguns do Ubuntu, caso ninguém ainda tenha submetido

**Comment by onhernandes** [comment]
Beleza! =)

**Comment by gustavofreze** [comment]
Não foi criado o tutorial.
