### ISSUE TITLE
Tutorial de instalação do PHP Composer no Ubuntu

### ISSUE THREAD

**Issue by onhernandes** [backend-br/como-instalar-xyz#16]

**Comment by girol** [comment]
Olá!

Posso fazer esse :)

Uma dúvida: os tutoriais são pra ambiente de desenvolvimento ou produção?

**Comment by onhernandes** [comment]
@girol massa! Então, os tutoriais não tem foco nesse sentido, porque geralmente isso varia nas configurações em si. Tu pode fazer um único tutorial de instalação e colocar umas dicas pra produção no meio =)

**Comment by girol** [comment]
Nice! Eu perguntei pra dar um foco maior no que vou escrever. Vou preparar já :D
