### ISSUE TITLE
Tutorial de instalação do Android Studio no Ubuntu

### ISSUE THREAD

**Issue by onhernandes** [backend-br/como-instalar-xyz#26]

**Comment by martinsrso** [comment]
Poderia fazê-lo?

**Comment by WilliamCunhaCardoso** [comment]
Lembre de em Arch ver a questão do /tmp. E Abordar não só deb, zip e afins como também snap e flatpak. bem como usas diferenças

**Comment by gustavofreze** [comment]
Não foi criado o tutorial.
