### ISSUE TITLE
Tutorial de instalação do NGINX no Ubuntu

### ISSUE THREAD

**Issue by onhernandes** [backend-br/como-instalar-xyz#27]

**Comment by paulohrpinheiro** [comment]
Salve, @onhernandes , tudo na paz? Eu posso fazer, é só deixar essa vontade aqui registrada e ir fazendo, ou precisa de mais alguma coisa?

**Comment by onhernandes** [comment]
Opa @paulohrpinheiro marquei a label `em progresso` aqui, é só isso, valeu!

**Comment by paulohrpinheiro** [comment]
Bora trabalhar!

**Comment by gustavofreze** [comment]
[Tutorial](https://github.com/backend-br/como-instalar-xyz/blob/master/tutoriais/nginx/linux/ubuntu.md) concluído.
