### ISSUE TITLE
Tutorial de instalação do Ruby no Windows

### ISSUE THREAD

**Issue by onhernandes** [backend-br/como-instalar-xyz#40]

**Comment by andremeireles** [comment]
Li em algum lugar que o [Scoop.sh](https://scoop.sh) permite a instalação do Ruby no Windows.
[Repositório no Github](https://github.com/lukesampson/scoop)

**Comment by onhernandes** [comment]
Que massa @andremeireles !

Tu pode fazer um tutorial pra nós? Seria ótimo! =)

**Comment by alismed** [comment]
feito.
já foi publicado

**Comment by andremeireles** [comment]
@onhernandes, ainda é possível incluir uma opção de instalação pelo scoop?
Com ele você pode instalar mais de uma versão do ruby, permitindo trocar de versão rapidamente.

**Comment by onhernandes** [comment]
@andremeireles sim! Tu pode mandar um PR alterando?
