### ISSUE TITLE
Tutorial de instalação do Pyenv no Ubuntu

### ISSUE THREAD

**Issue by rafaeltardivo** [backend-br/como-instalar-xyz#48]
Tutorial de como instalar pyenv (gerenciador de múltiplas versões Python) no Ubuntu. Faz sentido para o propósito do repo? Se fizer, me disponho a criar o conteúdo.

**Comment by onhernandes** [comment]
Sim! Você pode colocar na divisão "Outros": https://github.com/backend-br/como-instalar-xyz#outros
