### ISSUE TITLE
Tutorial de instalação do virtualenv + virtualenvwrapper (Python) no Ubuntu

### ISSUE THREAD

**Issue by rafaeltardivo** [backend-br/como-instalar-xyz#49]
Faz sentido para o repo? Se sim, me disponho a fazer.

**Comment by onhernandes** [comment]
Sim! Pode colocar aqui: https://github.com/backend-br/como-instalar-xyz#outros

=)

**Comment by gustavofreze** [comment]
Não foi criado o tutorial.
