### ISSUE TITLE
Tutorial de instalação do Ruby no Arch Linux

### ISSUE THREAD

**Issue by robsonsilv4** [backend-br/como-instalar-xyz#59]
Já tem um tutorial que engloba todas distribuições, utilizando o RVM, mas como utilizo o Arch Linux a um tempo e gosto mais de gerenciar as instalações utilizando o seu próprio gerenciador de pacotes, vou adicionar esta maneira, já que é também a forma que a Wiki recomenda.

**Comment by gustavofreze** [comment]
Não foi criado o tutorial.
