### ISSUE TITLE
Site colaborativo para postagens do como-instalar-xyz

### ISSUE THREAD

**Issue by exata0mente** [backend-br/como-instalar-xyz#64]
Olá a todos! Venho em paz.

Acho a iniciativa super bacana e acredito que podemos expandir a divulgação desse conteúdo.

Possuo um [site](https://exata0mente.com.br/) construído com Jerkyll e hospedado no Github (utilizando o serviço do github pages) ao qual postamos resoluções de exercícios que aparecem em livros que vemos no decorrer da vida acadêmica. **este site é totalmente colaborativo** e aberto para qualquer pessoa realizar postagens, alterações, e etc. 

Referente aos exercícios, o carro chefe do site, são de teor mais técnicos e geralmente voltados à computação, sempre aparece algum programa para instalar ou sugestão de programas. Penso que podemos trabalhar das seguintes formas:

## Postagem de _como-instalar-xy_
Seria basicamente os tutoriais aqui inseridos porém publicado no site. [Postar](https://github.com/exata0mente/exata0mente.github.io/blob/master/docs/CONTRIBUTING.md) no site é muito simples e pode ser inclusive utilizando o markdown.

O site está bem elementar mas a ideia é criar uma série de postagens *como-instalar-xyz* para divulgar o trabalho. 

As postagens podem ser diretamente relacionadas a conteúdos que já existem no próprio site, como será citado abaixo.

Por exemplo: Temos resposta de exercícios do livro [Treinamento em Linguagem C](https://exata0mente.com.br/indice/livro/treinamento_em_linguagem_c) da Victorine Mizrahi. Obviamente este livro usa extensivamente a linguagem C. Podemos então ter postagens sobre como instalar IDEs, Editores de Textos e até Compiladores.

Conseguiremos então divulgar a comunidade backend-br, exata0mente e também pode servir de portifólio para quem tenha interesse em realizar postagens.

## Tecnologias de contribuição

Conforme dito, o site é colaborativo e disponível para qualquer pessoa realizar postagens, alterações, sugestões e até praticar CSS (por exemplo). Para que isso seja possível utilizamos o gerador de sites estáticos Jerkyll.

A sua instalação não é tão elementar, ainda mais pelo fato de que é necessário possuir o Ruby instalado.

Então (já fica como sugestão), criar um tutorial de como instalar estes programas. Se possível criar até uma postagem como dito anteriormente pois acredito que atenderá não só ao site mas a pessoas de fora do site também. O(s) conteúdo(s) será referenciado no meu [README.md](https://github.com/exata0mente/exata0mente.github.io#criando-um-parquinho)

Bom, acho que é isso, caso queiram mais detalhamentos fico à disposição.

Fique a vontade também para encerrar esta issue caso não tenha relação com o tema do repositório.

Forte abraço! 
https://github.com/exata0mente/

**Comment by Miguel-EpicJS** [comment]
Achei muito interessante a ideia, mas o ultimo post foi de 2019, ainda posso contribuir?

**Comment by onhernandes** [comment]
Oi @exata0mente 

A ideia é ótima. A gente já possui um site (que tá fora do ar agora), e pretendíamos publicar lá, mas eu não to com tempo pra mexer nisso agora, infelizmente.

A licença do repositório te dá liberdade pra copiar, modificar e publicar o conteúdo como quiser. Só não vamos usar as publicações no seu site, como oficiais (em nome da comunidade BackEnd Brasil), mas vamos compartilhar :)

E além do mais, quanto mais divulgação, melhor ainda :)

Muitíssimo obrigado!

**Comment by gustavofreze** [comment]
Aparentemente abandonado.
