### ISSUE TITLE
Sugestão de categoria

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [backend-br/como-instalar-xyz#67]
Criar uma categoria para apenas SQL:
MySQL, Oracle SQL, MSSQL, e etc.

**Comment by onhernandes** [comment]
Gostei da ideia, acredito que seria melhor separar em outra categoria apenas para bancos de dados, né?

**Comment by WilliamCunhaCardoso** [comment]
Isso

**Comment by Vagnerlg** [comment]
Primeiramente parabéns pela iniciativa, acho TB que deveria ter uma categoria para instalação de "starter" de projetos e framework, visto que estes a vezes demandam mais configurar além da instalação básica prevista.

**Comment by onhernandes** [comment]
@WilliamCunhaCardoso e @Vagnerlg se liga: https://github.com/backend-br/como-instalar-xyz/pull/69
