### ISSUE TITLE
Tutorial de instalação e inicialização de projeto Laravel

### ISSUE THREAD

**Issue by Vagnerlg** [backend-br/como-instalar-xyz#70]
Tutorial com passos para instalação de Laravel mais um projeto inicial tipo hello work

**Comment by Vagnerlg** [comment]
Vou fazer esse

**Comment by gustavofreze** [comment]
[Tutorial](https://github.com/backend-br/como-instalar-xyz/blob/master/tutoriais/laravel/linux/ubuntu.md) concluído.
