### ISSUE TITLE
Tutorial de instalação do Chocolatey no Windows

### ISSUE THREAD

**Issue by vinibeloni** [backend-br/como-instalar-xyz#79]
Chocolatey é um gerenciador de pacotes para o windows, é extremamente útil pra instalar vários tipos de programas (até o Visual Studio tem lá)

**Comment by vinibeloni** [comment]
Vou fazer este

**Comment by gustavofreze** [comment]
[Tutorial](https://github.com/backend-br/como-instalar-xyz/blob/master/tutoriais/chocolatey/windows/windows.md) concluído.
