### ISSUE TITLE
Criação de um novo repositorio: como-fazer-xyz

### ISSUE THREAD

**Issue by Miguel-EpicJS** [backend-br/como-instalar-xyz#87]
Seria interessante a comunidade `backend-br` ter um repositório parecido com esse, mas em vez de instalar, como fazer.

Mais alguém estaria interessado nessa ideia?

**Comment by reginaldojunior** [comment]
Acho interessante, mas qual seria o tipo de conteúdo nesse repositório? O como instalar já nao seria algo nesse sentido? Seria algo mais abragente como tópicos de por exemplo, como fazer um chat real time?

**Comment by Miguel-EpicJS** [comment]
Isso, seria mais ou menos isso mesmo, pois aqui pelo nome do repo da a entender que é apenas instalação, o como fazer seria mostrando na prática ;)

**Comment by onhernandes** [comment]
@Miguel-EpicJS a ideia é ótima. 

A gente precisa definir também, um limite ou tamanho pra cada projeto. Pensei em talvez pegar uma dessas listas de ideias pra apps ou projetos simples, e fazer uma série desses projetos em cada linguagem, por exemplo. O ruim de qualquer forma é que precisamos manter um controle pra não termos projetos super enormes - por outro lado, precisa ter o cuidado de não ter 15 projetos em uma linguagem sobre coisas muito simples, como operações matemáticas comuns, etc.

**Comment by Miguel-EpicJS** [comment]
@onhernandes poderiamos utilizar as ideias desse repositorio como base: https://github.com/florinpop17/app-ideas

Ela da umas ideias bem legais.
