### ISSUE TITLE
ideias para melhorar o repositório como-instalar-xyz

### ISSUE THREAD

**Issue by ghost** [backend-br/como-instalar-xyz#91]
Olá a todos!

Gostaria de trazer algumas ideias para melhorar este repositório:
- estava pensando em criar uma versão online do como-instalar-xyz no GitHub Pages com docsify, o que pensam da ideia?
- estava pensando em oferecer um guia de instalação de programas, assim como, várias linguagens de programação antigas, atuais de diferentes sistemas operacionais também.

*O que vocês pensam sobre essas duas ideias?*

**Comment by gustavofreze** [comment]
Sinta-se à vontade, toda contribuição é bem-vinda.
